# service: aws-sls-employee-api
# frameworkVersion: '2 || 3'

# custom:
#   tableName: 'Employees'

# provider:
#   name: aws
#   runtime: nodejs12.x
#   lambdaHashingVersion: '20201221'
#   iam:
#     role:
#       statements:
#         - Effect: Allow
#           Action:
#             - dynamodb:Query
#             - dynamodb:Scan
#             - dynamodb:GetItem
#             - dynamodb:PutItem
#             - dynamodb:UpdateItem
#             - dynamodb:DeleteItem
#           Resource:
#             - Fn::GetAtt: [ EmployeeTable, Arn ]
#   environment:
#     TABLENAME: ${self:custom.tableName}
#     NODE_ENV: 'production'
#     REGION: 'ap-south-1'

# functions:
#   api:
#     handler: handler.handler
#     layers:
#       - arn:aws:lambda:ap-south-1:312828120454:layer:dep:1
#     events:
#       - httpApi: '*'

# resources:
#   Resources:
#     EmployeeTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         AttributeDefinitions:
#           - AttributeName: LocationID
#             AttributeType: S
#           - AttributeName: EmpCode
#             AttributeType: S
#         KeySchema:
#           - AttributeName: LocationID
#             KeyType: HASH
#           - AttributeName: EmpCode
#             KeyType: RANGE
#         BillingMode: PAY_PER_REQUEST
#         TableName: ${self:custom.tableName}

service: serverless-rest-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: items
          method: post
  read:
    handler: handler.read
    events:
      - http:
          path: items/{id}
          method: get
  update:
    handler: handler.update
    events:
      - http:
          path: items/{id}
          method: put
  delete:
    handler: handler.delete
    events:
      - http:
          path: items/{id}
          method: delete

resources:
  Resources:
    ItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Items
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
